AWSTemplateFormatVersion: '2010-09-09'
Description: Orchestrate Data Preprocessing Job in AWS Glue

Resources:
  DataOpsGlueIngestionJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "dataops-glue-ingestion-job"
      Role: "arn:aws:iam::988964411479:role/LabRole"
      Command:
        Name: "glueetl"
        ScriptLocation: "s3://datasource-dataops-group5-bucket/script-ingestion/ingestion.py"
        PythonVersion: "3"
      GlueVersion: "4.0"
      NumberOfWorkers: 10
      WorkerType: "G.1X"

  DataOpsGluePreProcessingJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "dataops-glue-preprocessing-job"
      Role: "arn:aws:iam::988964411479:role/LabRole"
      Command:
        Name: "glueetl"
        ScriptLocation: "s3://datalake-dataops-group5-bucket/script-preprocessing/pre_processing.py"
        PythonVersion: "3"
      GlueVersion: "4.0"
      NumberOfWorkers: 10
      WorkerType: "G.1X"
      DefaultArguments:
        '--TempDir': 's3://datalake-dataops-group5-bucket-temp/temp/'
        '--job-language': 'python'

  DataOpsGlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: "dataops-glue-workflow"
      Description: "Workflow to orchestrate ingestion and preprocessing jobs"

  DataOpsWorkflowStartTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: "dataops-workflow-start-trigger"
      Type: ON_DEMAND
      Description: "Trigger to start the workflow"
      Actions:
        - JobName: !Ref DataOpsGlueIngestionJob
      WorkflowName: !Ref DataOpsGlueWorkflow

  DataOpsIngestionToPreProcessingTrigger:
    Type: AWS::Glue::Trigger
    DependsOn:
      - DataOpsGlueIngestionJob
      - DataOpsGluePreProcessingJob
    Properties:
      Name: "dataops-glue-trigger-ingestion-to-preprocessing"
      Description: "Trigger to start preprocessing job after ingestion job completes"
      Type: CONDITIONAL
      StartOnCreation: true
      Actions:
        - JobName: !Ref DataOpsGluePreProcessingJob
      Predicate:
        Conditions:
          - JobName: !Ref DataOpsGlueIngestionJob
            LogicalOperator: EQUALS
            State: SUCCEEDED
      WorkflowName: !Ref DataOpsGlueWorkflow

Outputs:
  PreProcessingJobName:
    Description: 'Name of the Glue Pre-Processing Job'
    Value: !Ref DataOpsGluePreProcessingJob
  WorkflowName:
    Description: 'Name of the Glue Workflow'
    Value: !Ref DataOpsGlueWorkflow
  StartTriggerName:
    Description: 'Name of the Workflow Start Trigger'
    Value: !Ref DataOpsWorkflowStartTrigger
