AWSTemplateFormatVersion: '2010-09-09'
Description: Orchestrate Data Ingestion and Preprocessing Jobs in AWS Glue using Workflow

Resources:
  # Define the Glue Workflow
  DataOpsGlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: "dataops-glue-workflow"
      Description: "Workflow to orchestrate ingestion and preprocessing jobs"

  # Define the Ingestion Job
  DataOpsGlueIngestionJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "dataops-glue-ingestion-job"
      Role: "arn:aws:iam::988964411479:role/LabRole"
      Command:
        Name: "glueetl"
        ScriptLocation: "s3://datasource-dataops-group5-bucket/script-ingestion/ingestion.py"
        PythonVersion: "3"
      GlueVersion: "4.0"
      NumberOfWorkers: 10
      WorkerType: "G.1X"
      MaxRetries: 1

  # Define the Preprocessing Job
  DataOpsGluePreProcessingJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "dataops-glue-preprocessing-job"
      Role: "arn:aws:iam::988964411479:role/LabRole"
      Command:
        Name: "glueetl"
        ScriptLocation: "s3://datalake-dataops-group5-bucket/script-preprocessing/pre_processing.py"
        PythonVersion: "3"
      GlueVersion: "4.0"
      NumberOfWorkers: 10
      WorkerType: "G.1X"
      DefaultArguments:
        '--TempDir': 's3://datalake-dataops-group5-bucket-temp/temp/'
        '--job-language': 'python'
      MaxRetries: 1

  # Trigger to start the Ingestion Job
  DataOpsStartIngestionTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: "dataops-glue-trigger-start-ingestion"
      Type: ON_DEMAND
      StartOnCreation: true
      Actions:
        - JobName: !Ref DataOpsGlueIngestionJob

  # Trigger for starting Preprocessing Job after Ingestion Job completes successfully
  DataOpsIngestionToPreProcessingTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: "dataops-glue-trigger-ingestion-to-preprocessing"
      Description: "Trigger to start preprocessing job after ingestion job completes"
      Type: CONDITIONAL
      StartOnCreation: true
      Actions:
        - JobName: !Ref DataOpsGluePreProcessingJob
      Predicate:
        Conditions:
          - JobName: !Ref DataOpsGlueIngestionJob
            LogicalOperator: EQUALS
            State: SUCCEEDED
      WorkflowName: !Ref DataOpsGlueWorkflow

  # Manually trigger the Glue Workflow
  DataOpsGlueWorkflowStartTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: "dataops-glue-start-trigger"
      Type: ON_DEMAND
      Actions:
        - WorkflowRunProperties:
            WorkflowName: !Ref DataOpsGlueWorkflow
      StartOnCreation: true

Outputs:
  WorkflowName:
    Description: 'Name of the Glue Workflow'
    Value: !Ref DataOpsGlueWorkflow

  PreProcessingJobName:
    Description: 'Name of the Glue Pre-Processing Job'
    Value: !Ref DataOpsGluePreProcessingJob
