AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GlueJobIngestion:
    Type: AWS::Glue::Job
    Properties:
      Name: "glue-job-ingestion"
      Role: "arn:aws:iam::233359079168:role/LabRole"  # Replace with the ARN of the 'Lab Role'
      Command:
        Name: "glueetl"
        ScriptLocation: "s3://datasource-dataops-group5/script-ingestion/ingestion.py"  # Update with your S3 path
      DefaultArguments:
        "--job-language": "python"
      MaxRetries: 0
      GlueVersion: "4.0"
      WorkerType: "G.1X"
      NumberOfWorkers: 5

  GlueJobTransformation:
    Type: AWS::Glue::Job
    Properties:
      Name: "glue-job-transformation"
      Role: "arn:aws:iam::233359079168:role/LabRole"  # Replace with the ARN of the 'Lab Role'
      Command:
        Name: "glueetl"
        ScriptLocation: "s3://datalake-dataops-group5/script-transformation/pre_processing.py"  # Update with your S3 path
      DefaultArguments:
        "--job-language": "python"
        "--additional-python-modules": "pandas==1.1.0,pyarrow==2,awswrangler==2.7.0"  # Add any required modules here
      MaxRetries: 0
      GlueVersion: "4.0"
      WorkerType: "G.1X"
      NumberOfWorkers: 5
      Timeout: 288  # Optional: Set a timeout (in minutes) for the job
