AWSTemplateFormatVersion: '2010-09-09'
Description: Orchestrate Data Ingestion and Preprocessing Jobs in AWS Glue

Resources:
  LabRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "LabRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "GlueJobPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:CreateJob
                  - glue:StartJobRun
                  - glue:GetJob
                  - glue:UpdateJob
                  - glue:CreateTrigger
                  - glue:UpdateTrigger
                  - glue:DeleteTrigger
                  - glue:GetTrigger
                  - glue:StartTrigger
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - "arn:aws:s3:::datasource-dataops-group5/*"
                  - "arn:aws:s3:::datalake-dataops-group5/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  DataOpsGlueIngestionJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "dataops-glue-ingestion-job"
      Role: !GetAtt LabRole.Arn
      Command:
        Name: "glueetl"
        ScriptLocation: "s3://datasource-dataops-group5/script-ingestion/ingestion.py"
        PythonVersion: "3"
      GlueVersion: "4.0"
      NumberOfWorkers: 10
      WorkerType: "G.1X"

  DataOpsGluePreProcessingJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "dataops-glue-preprocessing-job"
      Role: !GetAtt LabRole.Arn
      Command:
        Name: "glueetl"
        ScriptLocation: "s3://datalake-dataops-group5/script-preprocessing/pre_processing.py"
        PythonVersion: "3"
      GlueVersion: "4.0"
      NumberOfWorkers: 10
      WorkerType: "G.1X"

  DataOpsIngestionToPreProcessingTrigger:
    Type: AWS::Glue::Trigger
    DependsOn:
      - DataOpsGlueIngestionJob
      - DataOpsGluePreProcessingJob
    Properties:
      Name: "dataops-glue-trigger-ingestion-to-preprocessing"
      Description: "Trigger to start preprocessing job after ingestion job completes"
      Type: CONDITIONAL
      StartOnCreation: true
      Actions:
        - JobName: "dataops-glue-preprocessing-job"
      Predicate:
        Conditions:
          - JobName: "dataops-glue-ingestion-job"
            LogicalOperator: EQUALS
            State: SUCCEEDED
      Tags:
        - Key: "Environment"
          Value: "Production"
