AWSTemplateFormatVersion: '2010-09-09'
Description: Orchestrate Ingestion and PreProcessing Jobs in AWS Glue

Resources:
  # Create the AWS Glue ingestion job
  IngestionJob:
    Type: AWS::Glue::Job
    Properties:
      Name: glue-job-ingestion-group5
      Role: arn:aws:iam::233359079168:role/LabRole
      Command:
        Name: glueetl
        ScriptLocation: s3://datasource-dataops-group5/script-ingestion/ingestion.py
        PythonVersion: 3
      GlueVersion: '4.0'
      MaxCapacity: 2.0
      Timeout: 2880  # 48 hours
      NumberOfWorkers: 10
      WorkerType: G.1X

  # Create the AWS Glue preprocessing job
  PreProcessingJob:
    Type: AWS::Glue::Job
    Properties:
      Name: glue-job-preprocessing
      Role: arn:aws:iam::233359079168:role/LabRole
      Command:
        Name: glueetl
        ScriptLocation: s3://datalake-dataops-group5/script-preprocessing/preprocessing.py
        PythonVersion: 3
      GlueVersion: '4.0'
      MaxCapacity: 2.0
      Timeout: 2880  # 48 hours
      NumberOfWorkers: 10
      WorkerType: G.1X

  # Create a trigger to start preprocessing after ingestion job completes
#   IngestionToPreProcessingTrigger:
#     Type: AWS::Glue::Trigger
#     Properties:
#       Name: glue-trigger-ingestion-preprocessing
#       Description: Trigger to start preprocessing job after ingestion job completes
#       Type: CONDITIONAL
#       Actions:
#         - JobName: glue-job-preprocessing
#       Predicate:
#         Conditions:
#           - LogicalOperator: EQUALS
#             JobName: glue-job-ingestion-group5
#             State: SUCCEEDED

# Outputs:
#   IngestionJobName:
#     Value: glue-job-ingestion-group5
#     Description: The name of the ingestion job

#   PreProcessingJobName:
#     Value: glue-job-preprocessing
#     Description: The name of the preprocessing job

#   TriggerName:
#     Value: glue-trigger-ingestion-preprocessing
#     Description: The name of the trigger

