AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 's3-bucket-raw-data-unique-123456'
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private