name: Deploy CloudFormation and Run AWS Glue Job

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload Python script to S3
      run: |
        aws s3 cp ingestion.py s3://datasource-dataops-group5/script-ingestion/
        aws s3 cp pre_processing.py s3://datalake-dataops-group5/script-preprocessing/

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file glue-job-template.yaml \
          --stack-name glue-job-stack-workflow \
          --capabilities CAPABILITY_IAM

    - name: Start Glue Job
      run: |
        aws glue start-job-run --job-name glue-job-ingestion-preprocessing
