AWSTemplateFormatVersion: '2010-09-09'
Description: Orchestrate Data Preprocessing Job in AWS Glue

Parameters:
  ScriptsBucket:
    Type: String
    Default: "dbda-scripts-bucket"
    Description: "The S3 bucket where the Glue scripts are stored"

  DatalakeTempBucket:
    Type: String
    Default: "datalake-dbda-group5-temp"
    Description: "The S3 bucket for temporary Glue files"

  GlueRoleArn:
    Type: String
    Description: "The IAM role ARN for Glue jobs"

Resources:
  DataOpsGlueIngestionJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "dataops-glue-ingestion-job"
      Role: !Ref GlueRoleArn
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://${ScriptsBucket}/script-ingestion/ingestion.py"
        PythonVersion: "3"
      GlueVersion: "4.0"
      NumberOfWorkers: 10
      WorkerType: "G.1X"

  DataOpsGluePreProcessingJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "dataops-glue-preprocessing-job"
      Role: !Ref GlueRoleArn
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://${ScriptsBucket}/script-pre-processing/pre_processing.py"
        PythonVersion: "3"
      GlueVersion: "4.0"
      NumberOfWorkers: 10
      WorkerType: "G.1X"
      DefaultArguments:
        '--TempDir': !Sub "s3://${DatalakeTempBucket}/temp/"
        '--job-language': 'python'

  DataOpsGlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: "dataops-glue-workflow"
      Description: "Workflow to orchestrate ingestion and preprocessing jobs"

  DataOpsWorkflowStartTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: "dataops-workflow-start-trigger"
      Type: ON_DEMAND
      Description: "Trigger to start the workflow"
      Actions:
        - JobName: !Ref DataOpsGlueIngestionJob
      WorkflowName: !Ref DataOpsGlueWorkflow

  DataOpsIngestionToPreProcessingTrigger:
    Type: AWS::Glue::Trigger
    DependsOn:
      - DataOpsGlueIngestionJob
      - DataOpsGluePreProcessingJob
    Properties:
      Name: "dataops-glue-trigger-ingestion-to-preprocessing"
      Description: "Trigger to start preprocessing job after ingestion job completes"
      Type: CONDITIONAL
      StartOnCreation: true
      Actions:
        - JobName: !Ref DataOpsGluePreProcessingJob
      Predicate:
        Conditions:
          - JobName: !Ref DataOpsGlueIngestionJob
            LogicalOperator: EQUALS
            State: SUCCEEDED
      WorkflowName: !Ref DataOpsGlueWorkflow

Outputs:
  PreProcessingJobName:
    Description: 'Name of the Glue Pre-Processing Job'
    Value: !Ref DataOpsGluePreProcessingJob
  WorkflowName:
    Description: 'Name of the Glue Workflow'
    Value: !Ref DataOpsGlueWorkflow
  StartTriggerName:
    Description: 'Name of the Workflow Start Trigger'
    Value: !Ref DataOpsWorkflowStartTrigger
