name: Run PySpark Job

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-pyspark-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyspark

    - name: Download JAR files
      run: |
        wget https://github.com/SahilTalathi142001/group-5-project/blob/main/hadoop-aws-2.7.3.jar
        wget https://github.com/SahilTalathi142001/group-5-project/blob/main/aws-java-sdk-1.11.30.jar

    - name: Run PySpark job
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: |
        spark-submit --jars hadoop-aws-2.7.3.jar,aws-java-sdk-1.11.30.jar s3_transfer.py
